### ISSUE TITLE
Usernames or actions with capitals in them can cause inaccurate data

### ISSUE THREAD

**Issue by JamesIves** [geritol/count-actions-users#1]
Looking at this it looks like action names with capitals in it can cause problems. When placing `JamesIves/github-pages-deploy-action` in the box it results in `N/A`. When using the all-lowercase version it responds with `44` users which I don't believe is accurate. 

[![JamesIves/github-pages-deploy-action user count](https://img.shields.io/endpoint?url=https%3A%2F%2Factions.geritol.tech%2Fapi%2FJamesIves%2Fgithub-pages-deploy-action%3Fformat%3Dshields.io&cacheSeconds=3600)](https://actions.geritol.tech/JamesIves/github-pages-deploy-action)

[![JamesIves/github-pages-deploy-action user count](https://img.shields.io/endpoint?url=https%3A%2F%2Factions.geritol.tech%2Fapi%2FJamesIves%2Fgithub-pages-deploy-action%3Fformat%3Dshields.io&cacheSeconds=3600)](https://actions.geritol.tech/JamesIves/github-pages-deploy-action)

Overall really cool service! This provides more insight into user usage than the actual insights dashboard its self.

**Comment by geritol** [comment]
@JamesIves 
What do you think would be an accurate result?
The service is using the following search: 
[JamesIves/github-pages-deploy-action](https://github.com/search?l=YAML&q=JamesIves%2Fgithub-pages-deploy-action&type=Code)
(checks for references in yaml files)
Seems to correctly return 44 for that.

Will invesitgate the casing issue!

**Comment by JamesIves** [comment]
I'd expect it to at least be in the thousands. after investigating it looks to be an issue with GItHub specifically, seems that all results from GitHubs site wide search only yields results in lowercase as opposed to mixed casing. I'll open up a ticket with GitHub and see what they say.

**Comment by geritol** [comment]
Yeah, altering the search query, shows around 45.000 users.
https://github.com/search?l=YAML&q=%2Fgithub-pages-deploy-action&type=Code

Quite weird.
Please tag me in the ticket, thank you!
